version: "3.8"

services:
  vite-app:
    build:
      context: ./frontend/pizza-orders
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - node-ts-app
    networks:
      - app-network

  node-ts-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URL=http://localhost:8080
      - DB_URI=mongodb://mongodb:27018/pizza-orders
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
