import { Texts } from "../types/general";

export const texts: Texts = {
  en: {
    orders: "Orders",
    filterBy: "Filter by",
    sortBy: "Sort",
    a_z: "A-Z",
    z_a: "Z-A",
    NewsFirst: "News First (By Date)",
    All: "All",
    Received: "Received",
    Preparing: "Preparing",
    Ready: "Ready",
    EnRoute: "EnRoute",
    Delivered: "Delivered",
    showOnMap: "Show on Map",
    location: "Location",
    items: "Items",
    cocacola: "Coca-Cola",
    sprite: "Sprite",
    water: "Water",
    fanta: "Fanta",
    pizza: "Pizza",
    salad: "Salad",
    drink: "Drink",
    with: "with",
    peppers: "peppers",
    cheese: "Cheese",
    pepperoni: "Pepperoni",
    mushrooms: "Mushrooms",
    olives: "Olives",
    green: "Green",
    onions: "Onions",
    bacon: "Bacon",
    order: "Order",
    ["no."]: "No.",
    settings: "Settings",
    ok: "OK",
    cancel: "Cancel",
    timeToGetData: "Time to get data (in milliseconds)",
  },
  heb: {
    orders: "הזמנות",
    filterBy: "סנן לפי",
    sortBy: "מיין לפי",
    a_z: "א-ב",
    z_a: "ב-א",
    NewsFirst: "חדשות ראשונות (לפי תאריך)",
    All: "הכל",
    Received: "התקבל",
    Preparing: "בהכנה",
    Ready: "מוכן",
    EnRoute: "בדרך",
    Delivered: "נמסר",
    showOnMap: "הצג על המפה",
    location: "מיקום",
    items: "פריטים",
    cocacola: "קוקה-קולה",
    sprite: "ספרייט",
    water: "מים",
    fanta: "פנטה",
    pizza: "פיצה",
    salad: "סלט",
    drink: "שתייה",
    with: "עם",
    peppers: "פלפלים",
    cheese: "גבינה",
    pepperoni: "פפרוני",
    mushrooms: "פטריות",
    olives: "זיתים",
    onions: "בצל",
    bacon: "בייקון",
    order: "הזמנה",
    ["no."]: "מספר",
    settings: "הגדרות",
    ok: "אישור",
    cancel: "ביטול",
    timeToGetData: "זמן לקבלת נתונים (במילישניות)",
  },
};
